name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore TestProjectN1

    - name: Build
      run: dotnet build --configuration Release TestProjectN1

    - name: Run Tests and Generate XML Report
      run: |
        cd TestProjectN1
        dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../TestResults/ /p:UseSourceLink=true
        dotnet test --configuration Release --no-build

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.8.12
      if: success()

    - name: Generate HTML Report
      run: |
        dotnet reportgenerator "-reports:../TestResults/coverage.cobertura.xml" "-targetdir:coverage" -reporttypes:HtmlInline_AzurePipelines
      if: success()

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: coverage
